// <auto-generated />
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(BowlingDbContextWithStub))]
    [Migration("20221016232038_myFirstMigration")]
    partial class myFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Entities.PlayerEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Player", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Image = "imageMickael.png",
                            Name = "Mickael"
                        },
                        new
                        {
                            ID = 2,
                            Image = "imageJeremy.png",
                            Name = "Jeremy"
                        },
                        new
                        {
                            ID = 3,
                            Image = "imageLucas.png",
                            Name = "Lucas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
